### PR TITLE
Bundle as Gem

### PR DESCRIPTION
**Pull request by Katee**
Bundles as a gem under the name `certificator` to fix https://github.com/agile-alliance-brazil/certificates/issues/10.

* Fixme: a fake email has been added for the author
* Many classes have been namespaced under "Certificator"
* `lib` folder has been reorganized
* Files in `spec` are no longer nested under `lib`
* Removed unused factory
* Added gem rake tasks
* Moved `lib/generate_certificates.rb` to `bin/generate_certificates`

I tested by making sure all specs passed and by running `bundle exec ruby ./bin/generate_certificates example --dry-run`.

### CODE REVIEW

**Comment by hugocorbucci** [comment]
Added a PR on your fork to fix the email and ensure our tests are passing (rubocop wasn't happy).

**Comment by Katee** [comment]
Ah! Good catch.

**Comment by hugocorbucci** [comment]
Perfect!  Thank you very much again  @Katee. Mind if I just squash those commits?

**Comment by Katee** [comment]
👍

**Comment by hugocorbucci** [comment]
Done! Thank you very much again! :)

**Pull request merged**
